# Generated by Django 2.1.7 on 2020-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Num', models.CharField(max_length=500, verbose_name=' Numerator Coefficients')),
                ('Den', models.CharField(max_length=500, verbose_name=' Denominator Coefficients')),
            ],
        ),
    ]
